name: 🪛 Quality tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  code-style:
    name: 💅 Code style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/traect:test-latest
      options: --user root
      env:
        PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run MyPy
        run: poetry run mypy src

  tests-and-coverage:
    name: 🪛 Tests and coverage
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/traect:test-latest
      options: --user root
      env:
        PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

    steps:
      - uses: actions/checkout@v4

      - name: Run tests and coverage
        run: |
          poetry run pytest tests \
            --cov=src \
            --cov-report=term-missing \
            -q \
            -ra \
            --durations=10
